LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ifeq ($(TARGET_BOARD_OMAP_CPU),4470)
LOCAL_SGX_CORE := 544_112
else
LOCAL_SGX_CORE := 540_120
endif

LOCAL_SRC_FILES := egl.c
LOCAL_CFLAGS := -Wall -Werror
LOCAL_LDFLAGS := -L $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_LDLIBS := -lIMGegl_SGX$(LOCAL_SGX_CORE)
libEGL_POWERVR_SGX54X: $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/libIMGegl_SGX$(LOCAL_SGX_CORE).so
LOCAL_MODULE := libEGL_POWERVR_SGX54X

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/egl
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
